class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token

  # csfr token is generated by the system, to make sure the user is a real user
  # for api, this needs to be skipped
  
end
